admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_login_check:
    path: /admin/login_check

admin_logout:
    path: /admin/logout
