<?php

namespace ModelBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTagSummary(){
        $qb = $this->createQueryBuilder('t')
            ->join('t.books', 'b')
            ->select('t as tag, count(b) as nb')
            ->groupBy('t.tagName');

        return $qb->getQuery()->getResult();
    }
}
